### ISSUE TITLE
Perdita informazioni DB

### ISSUE THREAD

**Issue by Veronica-De-Santis-JCMaxwell-5Ai** [Veronica-De-Santis-JCMaxwell-5Ai/CRI_management#32]
Nella tabella chiamate c'è l'attributo DATA, nel passaggio alla tabella emergenza l'attributo viene completamente perso

**Comment by Misael-Micciche-JCMaxwell-5Ai** [comment]
Il problema è risolto! grazie per averlo fatto notare
